class AppStrings {
  const AppStrings._();

  static const appName = 'MoneyFlow';
  static const home = '首页';
  static const records = '明细';
  static const addTransaction = '记一笔';
  static const statistics = '统计';
  static const settings = '设置';
  static const monthlyOverview = '本月概览';
  static const currentBalance = '当前结余';
  static const income = '收入';
  static const expense = '支出';
  static const balance = '结余';
  static const recentRecords = '最近记录';
  static const allRecords = '全部明细';
  static const today = '今天';
  static const thisMonth = '本月';
  static const categoryOverview = '分类概览';
  static const spendingTrend = '支出趋势';
  static const addTransactionTitle = '新增记录';
  static const amount = '金额';
  static const category = '分类';
  static const date = '日期';
  static const note = '备注';
  static const staticPreview = '静态预览';
  static const staticPreviewMessage = 'V0.3 使用领域模型展示记账流程，暂不保存数据。';
  static const saveRecord = '保存记录';
  static const accountSettings = '账户设置';
  static const categorySettings = '分类设置';
  static const dataSettings = '数据设置';
  static const appVersion = '版本';
  static const versionName = 'V0.3 领域模型版';
  static const localLedger = '本地账本';
  static const defaultCategoryPreview = '默认分类预览';
  static const noDatabaseInCurrentVersion = 'V0.3 暂不接数据库';
  static const previewAmount = '¥38.00';
  static const previewCategory = '餐饮';
  static const previewDate = '2026-05-02';
  static const previewNote = '工作日午餐';
  static const emptyTransactionTitle = '还没有记账记录';
  static const emptyTransactionMessage = 'V0.3 使用领域模型承载静态数据，后续版本会接入本地存储。';
  static const zeroAmount = '¥0.00';
}
